---
- hosts: "{{host_name}}"
  tasks:
  - name: Execute the rake script to get token
    shell: RAILS_ENV=production bundle exec rake support_token:get_token["support"]
    args:
      chdir: "{{rake_dir}}"
  - name: Copy the token to local system
    fetch:
      src: "{{token_src}}"
      dest: "{{token_dest}}/{{ansible_ssh_host}}/token.txt"
      flat: yes
