---
- hosts: "{{host_name}}"
  tasks:
  - name: Execute the rake script
    shell: RAILS_ENV=production bundle exec rake support_token:get_token["support"]
    args:
      chdir: /home/www/blip/current
  - name: Copy the token to local system
    fetch:
      src: /tmp/support_token.txt
      dest: /tmp/config-svc/store/blips/{{ansible_ssh_host}}/token.txt
      flat: yes
